const MODEL_DESC = {
    precision: '精确率',
    recall: '召回率',
    accuracy: '准确率',
    f1: 'f1值',
    recall_multilabel: '召回率',
    precision_multilabel: '精确率',
    f1_multilabel: 'f1值',
    acc_id: '准确率',
    precision_id: '精确率',
    recall_id: '召回率',
    f1_id: 'f1值',
    precision_ner: '精确率',
    recall_ner: '召回率',
    f1_ner: 'f1值',
    train_acc: '训练集准确率',
    val_acc: '验证集准确率',
    test_acc: '测试集准确率',
    map50: "平均mAP@0.5",
    map: "平均mAP@0.5:0.95",
    mp: "平均精确度",
    mr: "平均召回率",
    map50_bbox: "检测框平均mAP@0.5",
    map_bbox: "检测框平均mAP@0.5:0.95",
    mp_bbox: "检测框平均精确度",
    mr_bbox: "检测框平均召回率",
    map50_mask: "掩膜平均mAP@0.5",
    map_mask: "掩膜平均mAP@0.5:0.95",
    mp_mask: "掩膜平均精确度",
    mr_mask: "掩膜平均召回率",
    auc: "auc值",
    ks: "ks值"

}
export default MODEL_DESC